using System.Net;
using System.Text;
using Smplkit;
using Smplkit.Errors;
using Smplkit.Flags;
using Smplkit.Logging;
using Smplkit.Tests.Helpers;
using Xunit;

namespace Smplkit.Tests.Platform;

/// <summary>
/// Tests for the CRUD sub-clients (Config, Flags, Loggers, LogGroups,
/// Environments, ContextTypes, Contexts, AccountSettings) accessed through
/// the top-level <see cref="SmplClient"/>.
/// </summary>
public class PlatformSubClientsTests
{
    private static (SmplClient mgmt, MockHttpMessageHandler handler) Make(
        Func<HttpRequestMessage, Task<HttpResponseMessage>> respond)
    {
        var handler = new MockHttpMessageHandler(respond);
        var httpClient = new HttpClient(handler);
        var mgmt = new SmplClient(TestData.DefaultOptions(), httpClient);
        return (mgmt, handler);
    }

    private static HttpResponseMessage Json(string body, HttpStatusCode code = HttpStatusCode.OK)
        => new(code) { Content = new StringContent(body, Encoding.UTF8, "application/vnd.api+json") };

    // ------------------------------------------------------------------
    // Config sub-client (mgmt.Config)
    // ------------------------------------------------------------------

    [Fact]
    public void ConfigsClient_New_NullParent_ReturnsConfigWithoutParent()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var cfg = mgmt.Config.New("user-service");
        Assert.Equal("user-service", cfg.Id);
        Assert.Null(cfg.Parent);
    }

    [Fact]
    public void ConfigsClient_New_StringParent_SetsParent()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var cfg = mgmt.Config.New("user-service", parent: "common");
        Assert.Equal("common", cfg.Parent);
    }

    [Fact]
    public void ConfigsClient_New_ConfigParent_UsesParentId()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var parent = mgmt.Config.New("common");
        var cfg = mgmt.Config.New("user-service", parent: parent);
        Assert.Equal("common", cfg.Parent);
    }

    [Fact]
    public void ConfigsClient_New_BadParentType_Throws()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        Assert.Throws<ArgumentException>(() => mgmt.Config.New("x", parent: 42));
    }

    [Fact]
    public void ConfigsClient_New_AutoGeneratedName()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var cfg = mgmt.Config.New("user-service");
        Assert.Equal("User Service", cfg.Name);
    }

    [Fact]
    public async Task ConfigsClient_ListAsync_ParsesResponse()
    {
        var body = TestData.ConfigListJson();
        var (mgmt, _) = Make(_ => Task.FromResult(Json(body)));
        var configs = await mgmt.Config.ListAsync();
        Assert.Equal(2, configs.Count);
        Assert.Contains(configs, c => c.Id == "user_service");
    }

    [Fact]
    public async Task ConfigsClient_GetAsync_ParsesResponse()
    {
        var body = TestData.SingleConfigJson();
        var (mgmt, _) = Make(_ => Task.FromResult(Json(body)));
        var cfg = await mgmt.Config.GetAsync("user_service");
        Assert.Equal("user_service", cfg.Id);
        Assert.Equal("User Service", cfg.Name);
    }

    [Fact]
    public async Task ConfigsClient_DeleteAsync_SendsDelete()
    {
        HttpRequestMessage? captured = null;
        var (mgmt, _) = Make(req =>
        {
            captured = req;
            return Task.FromResult(Json("{}", HttpStatusCode.NoContent));
        });
        await mgmt.Config.DeleteAsync("user_service");
        Assert.NotNull(captured);
        Assert.Equal(HttpMethod.Delete, captured!.Method);
    }

    // ------------------------------------------------------------------
    // Flags sub-client (mgmt.Flags)
    // ------------------------------------------------------------------

    [Fact]
    public void FlagsClient_NewBooleanFlag_ReturnsBoolean()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var flag = mgmt.Flags.NewBooleanFlag("checkout-v2", false, description: "rollout");
        Assert.IsType<BooleanFlag>(flag);
        Assert.Equal("checkout-v2", flag.Id);
        Assert.Equal("BOOLEAN", flag.Type);
    }

    [Fact]
    public void FlagsClient_NewStringFlag_WithValues()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var flag = mgmt.Flags.NewStringFlag("banner", "red",
            values: new[] { new FlagValue("Red", "red"), new FlagValue("Blue", "blue") });
        Assert.IsType<StringFlag>(flag);
        Assert.Equal(2, flag.Values!.Count);
    }

    [Fact]
    public void FlagsClient_NewStringFlag_NullValues()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var flag = mgmt.Flags.NewStringFlag("banner", "red");
        Assert.Null(flag.Values);
    }

    [Fact]
    public void FlagsClient_NewNumberFlag()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var flag = mgmt.Flags.NewNumberFlag("retries", 3.0,
            values: new[] { new FlagValue("Low", 1), new FlagValue("High", 10) });
        Assert.IsType<NumberFlag>(flag);
        Assert.Equal(2, flag.Values!.Count);
    }

    [Fact]
    public void FlagsClient_NewJsonFlag()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var flag = mgmt.Flags.NewJsonFlag("theme", new Dictionary<string, object?> { ["mode"] = "light" });
        Assert.IsType<JsonFlag>(flag);
    }

    [Fact]
    public async Task FlagsClient_ListAsync_EmptyList()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("""{"data":[]}""")));
        var flags = await mgmt.Flags.ListAsync();
        Assert.Empty(flags);
    }

    [Fact]
    public async Task FlagsClient_GetAsync_NotFound_Throws()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("""{"errors":[{"detail":"not found"}]}""", HttpStatusCode.NotFound)));
        await Assert.ThrowsAsync<NotFoundException>(() => mgmt.Flags.GetAsync("missing"));
    }

    [Fact]
    public async Task FlagsClient_DeleteAsync_SendsDelete()
    {
        HttpRequestMessage? captured = null;
        var (mgmt, _) = Make(req =>
        {
            captured = req;
            return Task.FromResult(Json("{}", HttpStatusCode.NoContent));
        });
        await mgmt.Flags.DeleteAsync("checkout-v2");
        Assert.Equal(HttpMethod.Delete, captured!.Method);
    }

    // ------------------------------------------------------------------
    // Loggers sub-client (mgmt.Logging.Loggers)
    // ------------------------------------------------------------------

    [Fact]
    public void LoggersClient_New_DefaultManagedTrue()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var logger = mgmt.Logging.Loggers.New("showcase");
        Assert.True(logger.Managed);
        Assert.Equal("showcase", logger.Id);
        Assert.Equal("showcase", logger.Name); // id doubles as name
    }

    [Fact]
    public void LoggersClient_New_ExplicitManagedFalse()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var logger = mgmt.Logging.Loggers.New("showcase", managed: false);
        Assert.False(logger.Managed);
    }

    [Fact]
    public async Task LoggersClient_ListAsync_EmptyList()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("""{"data":[]}""")));
        var loggers = await mgmt.Logging.Loggers.ListAsync();
        Assert.Empty(loggers);
    }

    [Fact]
    public async Task LoggersClient_GetAsync_NotFound_Throws()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("""{"errors":[{"detail":"x"}]}""", HttpStatusCode.NotFound)));
        await Assert.ThrowsAsync<NotFoundException>(() => mgmt.Logging.Loggers.GetAsync("missing"));
    }

    [Fact]
    public async Task LoggersClient_DeleteAsync_SendsDelete()
    {
        HttpRequestMessage? captured = null;
        var (mgmt, _) = Make(req =>
        {
            captured = req;
            return Task.FromResult(Json("{}", HttpStatusCode.NoContent));
        });
        await mgmt.Logging.Loggers.DeleteAsync("showcase");
        Assert.Equal(HttpMethod.Delete, captured!.Method);
    }

    [Fact]
    public async Task LoggersClient_RegisterAsync_SendsBulkRequest()
    {
        HttpRequestMessage? captured = null;
        var (mgmt, _) = Make(req =>
        {
            captured = req;
            return Task.FromResult(Json("{}"));
        });
        await mgmt.Logging.Loggers.RegisterAsync(new[]
        {
            new LoggerSource("a", level: LogLevel.Info),
            new LoggerSource("b", resolvedLevel: LogLevel.Warn),
        });
        Assert.NotNull(captured);
        Assert.Equal(HttpMethod.Post, captured!.Method);
    }

    [Fact]
    public async Task LoggersClient_RegisterAsync_FlushFalse_BuffersWithoutHttp()
    {
        var requests = 0;
        var (mgmt, _) = Make(req =>
        {
            requests++;
            return Task.FromResult(Json("{}"));
        });

        await mgmt.Logging.Loggers.RegisterAsync(
            new[] { new LoggerSource("a", level: LogLevel.Info) },
            flush: false);

        Assert.Equal(0, requests);
        Assert.Equal(1, mgmt.Logging.Loggers.PendingCount);
    }

    [Fact]
    public async Task LoggersClient_FlushAsync_DrainsBufferInOneBulkRequest()
    {
        var requests = 0;
        var (mgmt, _) = Make(req =>
        {
            requests++;
            return Task.FromResult(Json("{}"));
        });

        await mgmt.Logging.Loggers.RegisterAsync(
            new[] { new LoggerSource("a", level: LogLevel.Info) }, flush: false);
        await mgmt.Logging.Loggers.RegisterAsync(
            new[] { new LoggerSource("b", resolvedLevel: LogLevel.Warn) }, flush: false);
        Assert.Equal(2, mgmt.Logging.Loggers.PendingCount);

        await mgmt.Logging.Loggers.FlushAsync();

        Assert.Equal(1, requests);
        Assert.Equal(0, mgmt.Logging.Loggers.PendingCount);
    }

    [Fact]
    public async Task LoggersClient_FlushAsync_EmptyBuffer_NoHttp()
    {
        var requests = 0;
        var (mgmt, _) = Make(req =>
        {
            requests++;
            return Task.FromResult(Json("{}"));
        });

        await mgmt.Logging.Loggers.FlushAsync();

        Assert.Equal(0, requests);
    }

    [Fact]
    public async Task LoggersClient_RegisterAsync_FlushTrue_DrainsPriorBuffer()
    {
        var requests = 0;
        var (mgmt, _) = Make(req =>
        {
            requests++;
            return Task.FromResult(Json("{}"));
        });

        await mgmt.Logging.Loggers.RegisterAsync(
            new[] { new LoggerSource("a", level: LogLevel.Info) }, flush: false);
        await mgmt.Logging.Loggers.RegisterAsync(
            new[] { new LoggerSource("b", resolvedLevel: LogLevel.Warn) }, flush: true);

        // One HTTP call sends both items.
        Assert.Equal(1, requests);
        Assert.Equal(0, mgmt.Logging.Loggers.PendingCount);
    }

    // ------------------------------------------------------------------
    // LogGroups sub-client (mgmt.Logging.LogGroups)
    // ------------------------------------------------------------------

    [Fact]
    public void LogGroupsClient_New_DefaultName()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var group = mgmt.Logging.LogGroups.New("billing");
        Assert.Equal("billing", group.Id);
        Assert.Equal("Billing", group.Name);
    }

    [Fact]
    public void LogGroupsClient_New_WithParent()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var group = mgmt.Logging.LogGroups.New("invoices", group: "billing");
        Assert.Equal("billing", group.Group);
    }

    [Fact]
    public void LogGroupsClient_New_ExplicitName()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("{}")));
        var group = mgmt.Logging.LogGroups.New("billing", name: "Custom");
        Assert.Equal("Custom", group.Name);
    }

    [Fact]
    public async Task LogGroupsClient_ListAsync_EmptyList()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("""{"data":[]}""")));
        var groups = await mgmt.Logging.LogGroups.ListAsync();
        Assert.Empty(groups);
    }

    [Fact]
    public async Task LogGroupsClient_GetAsync_NotFound_Throws()
    {
        var (mgmt, _) = Make(_ => Task.FromResult(Json("""{"errors":[{"detail":"x"}]}""", HttpStatusCode.NotFound)));
        await Assert.ThrowsAsync<NotFoundException>(() => mgmt.Logging.LogGroups.GetAsync("missing"));
    }

    [Fact]
    public async Task LogGroupsClient_DeleteAsync_SendsDelete()
    {
        HttpRequestMessage? captured = null;
        var (mgmt, _) = Make(req =>
        {
            captured = req;
            return Task.FromResult(Json("{}", HttpStatusCode.NoContent));
        });
        await mgmt.Logging.LogGroups.DeleteAsync("billing");
        Assert.Equal(HttpMethod.Delete, captured!.Method);
    }
}
